### ISSUE TITLE
Variable Injection via Attributes

### ISSUE THREAD

**Issue by kaeross** [ssddanbrown/haste#7]
Can we see an example of the variable used in the child template?

**Comment by ssddanbrown** [comment]
Examples now added in demo content. Can currently be seen in as per below files. Usage is the same for all types of variables.

 https://github.com/ssddanbrown/haste/blob/0b849ec1cc946b0fa5f5c112588c3f0338f28a5d/demo/parts/counter.html#L1-L10

https://github.com/ssddanbrown/haste/blob/0b849ec1cc946b0fa5f5c112588c3f0338f28a5d/demo/parts/button.html#L1-L3
