### ISSUE TITLE
Variable usage in template component names

### ISSUE THREAD

**Issue by kaeross** [ssddanbrown/haste#9]
# Feature request

Would be great to have a way to pass through variables as component names eg `<t:components.{{variable1}}_{{variable2}} />`

**Comment by ssddanbrown** [comment]
Added in aeaac54b01aa26ded3bfce18e7a8fce5473bd057 and is part of [Release v1.1](https://github.com/ssddanbrown/haste/releases/tag/v1.1.0).

Is defined a little differently, via a `:name` attribute like the below to try to keep with HTML tag formatting:

```html
@component=button
<t: :name="parts.{{component}}"/> 
```
